version: '3.8'

services:
  db:
    image: postgres_db
    build:
      context: .
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      TZ: Asia/Tokyo
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5433:5432
