version: '3.8'

services:
  db:
    image: postgres:12
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5433:5432